/* eslint-disable react/no-unescaped-entities */
/* eslint-disable jsx-a11y/alt-text */
import Head from "next/head";
import {
  AiFillGithub,
  AiFillLinkedin,
  AiFillTwitterCircle,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
// import profile from "../public/Dev-ed-wave.png";
import frontend from "../public/frontend.png";
import backend from "../public/backend.png";
import tool from "../public/tool.png";
import Image from "next/image";
import web1 from "../public/web1.png";
// import deved from "../public/Dev-ed-wave.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import web7 from "../public/web7.png";
import web8 from "../public/web8.png";
import web9 from "../public/web9.png";
import web10 from "../public/web10.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Mouhamed Mboup - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">metazo</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="CurriculumVitae.pdf"
                  alt="alt text"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Curriculum Vitae
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-8 py-10">
            <h3 className="text-1xl py-1 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Hey, it's Mouhamed Mboup
            </h3>
            <h4 className="text-1xl py-1 dark:text-white md:text-3xl">
              FullStack Developer
            </h4>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              This is my personal site, where you will find all the information
              about me.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://github.com/metazo" target="blank">
                {" "}
                <AiFillGithub />{" "}
              </a>
              <a
                href="https://www.linkedin.com/in/mouhamed-mboup-886309236/"
                target="blank"
              >
                <AiFillLinkedin />{" "}
              </a>
              <a href="https://twitter.com/med_mboup" target="blank">
                {" "}
                <AiFillTwitterCircle />{" "}
              </a>
            </div>

            <h5 className="text-3xl py-1 dark:text-white ">About me</h5>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              I am a 21 years old FullStack developer from France. I want to be
              as creative as possible by using my imagination and my
              intellectual abilities in my work. My goal is to make a site as
              beautiful and attractive as possible.
            </p>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 text-teal-600 font-medium dark:text-teal-400 ">
              Skills
            </h3>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={frontend} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">Frontend</h3>
              {/* <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p> */}
              {/* <h4 className="py-4 text-teal-600">Design Tools I Use</h4> */}
              <p className="text-gray-800 py-1">HTML / CSS</p>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">Angular</p>
              <p className="text-gray-800 py-1">React JS</p>
              <p className="text-gray-800 py-1">Sass</p>
              <p className="text-gray-800 py-1">Next JS</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={backend} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Backend</h3>
              {/* <p className="py-2">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p> */}
              {/* <h4 className="py-4 text-teal-600">Design Tools I Use</h4> */}
              <p className="text-gray-800 py-1">Node JS</p>
              <p className="text-gray-800 py-1">Java</p>
              <p className="text-gray-800 py-1">PHP</p>
              <p className="text-gray-800 py-1">Laravel</p>
              <p className="text-gray-800 py-1">MySQL</p>
              <p className="text-gray-800 py-1">MongoDB</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={tool} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Outils</h3>
              {/* <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p> */}
              {/* <h4 className="py-4 text-teal-600">Design Tools I Use</h4> */}
              <p className="text-gray-800 py-1">Git</p>
              <p className="text-gray-800 py-1">VsCode</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Firebase</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1  text-teal-600 font-medium dark:text-teal-400">
              Portofolio
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Below you will find some projects that I made ✨
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <a
                href="https://github.com/metazo/Dentist-website"
                target="blank"
              >
                {" "}
                <Image
                  className="rounded-lg object-cover"
                  // width={"100%"}
                  // height={"100%"}
                  // layout="responsive"
                  src={web1}
                />{" "}
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a
                href="https://github.com/metazo/landing-page-modern.git"
                target="blank"
              >
                <Image
                  className="rounded-lg object-cover"
                  // width={"100%"}
                  // height={"100%"}
                  // layout="responsive"
                  src={web9}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://github.com/metazo/quiz-symfony2" target="blank">
                <Image
                  className="rounded-lg object-cover"
                  // width={"100%"}
                  // height={"100%"}
                  // layout="responsive"
                  src={web2}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a
                href="https://github.com/metazo/PROJET-TWEET-ACADEMIE-EPITECH"
                target="blank"
              >
                <Image
                  className="rounded-lg object-cover"
                  // width={"100%"}
                  // height={"100%"}
                  // layout="responsive"
                  src={web3}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a
                href="https://github.com/metazo/portofolio-med.git"
                target="blank"
              >
                <Image
                  className="rounded-lg object-cover"
                  // width={"100%"}
                  // height={"100%"}
                  // layout="responsive"
                  src={web10}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a
                href="https://github.com/metazo/Puissance-4.git"
                target="blank"
              >
                <Image
                  className="rounded-lg object-cover"
                  // width={"100%"}
                  // height={"100%"}
                  // layout="responsive"
                  src={web4}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a
                href="https://github.com/metazo/FreeAds-laravel-EPITECH.git"
                target="blank"
              >
                <Image
                  className="rounded-lg object-cover"
                  // width={"100%"}
                  // height={"100%"}
                  // layout="responsive"
                  src={web5}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a
                href="https://github.com/metazo/simple-todos-react.git"
                target="blank"
              >
                <Image
                  className="rounded-lg object-cover"
                  // width={"100%"}
                  // height={"100%"}
                  // layout="responsive"
                  src={web6}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://github.com/metazo/Game-JS.git" target="blank">
                <Image
                  className="rounded-lg object-cover"
                  // width={"100%"}
                  // height={"100%"}
                  // layout="responsive"
                  src={web7}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a
                href="https://github.com/metazo/My-IRC---EPITECH.git"
                target="blank"
              >
                <Image
                  className="rounded-lg object-cover"
                  // width={"100%"}
                  // height={"100%"}
                  // layout="responsive"
                  src={web8}
                />
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
